name: Python environment information
description: "Print various Python environment information including installed packages"
inputs:
  output-path:
    description: "A file path to write the information to."
    required: False
    default: ""
  python_path:
    description: "The Python command for the environment to report on."
    required: False
    default: "python"
outputs:
  output:
    description: "The full informational output"
    value: ${{ steps.the_run.outputs.output }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: the_run
      run: |
        ${{ inputs.python_path }} $GITHUB_ACTION_PATH/info.py
      env:
        ACTION_FILE_PATH: ${{ inputs.output-path }}
        _PYTHON_INFO_ACTION_CONTEXT_GitHub: ${{ toJson(github) }}
        _PYTHON_INFO_ACTION_CONTEXT_Job: ${{ toJson(job) }}
        _PYTHON_INFO_ACTION_CONTEXT_Steps: ${{ toJson(steps) }}
        _PYTHON_INFO_ACTION_CONTEXT_Runner: ${{ toJson(runner) }}
        _PYTHON_INFO_ACTION_CONTEXT_Strategy: ${{ toJson(strategy) }}
        _PYTHON_INFO_ACTION_CONTEXT_Matrix: ${{ toJson(matrix) }}
